export interface BackgroundPreset {
  id: string;
  label: string;
  /** Same-origin path so canvases stay untainted. */
  src: string;
  /** CSS gradient used for the swatch in the picker. */
  swatch: string;
}

function grad(from: string, via: string, to: string): string {
  return `linear-gradient(135deg,${from} 0%,${via} 55%,${to} 100%)`;
}

/**
 * Framed-capture background catalogue. Ids are `g01…g16` so a retuned palette
 * never invalidates a stored `presetId`; the SVGs are generated by
 * `scripts/make-backgrounds.mjs` from the same stops.
 */
export const FRAME_PRESETS: BackgroundPreset[] = [
  { id: "g01", label: "Aurora", src: "/backgrounds/g01.svg", swatch: grad("#0f2027", "#2c7d7a", "#7be0c0") },
  { id: "g02", label: "Peach", src: "/backgrounds/g02.svg", swatch: grad("#ffb997", "#f4826c", "#d95f6e") },
  { id: "g03", label: "Lavender", src: "/backgrounds/g03.svg", swatch: grad("#8e7bd6", "#a78bfa", "#e0d4ff") },
  { id: "g04", label: "Midnight", src: "/backgrounds/g04.svg", swatch: grad("#0b1020", "#141a35", "#2b1e5c") },
  { id: "g05", label: "Forest", src: "/backgrounds/g05.svg", swatch: grad("#0b3d2e", "#1f7a4d", "#8fd694") },
  { id: "g06", label: "Sunrise", src: "/backgrounds/g06.svg", swatch: grad("#f5734c", "#e8465a", "#7a2a6b") },
  { id: "g07", label: "Ocean", src: "/backgrounds/g07.svg", swatch: grad("#1e3a8a", "#0ea5b7", "#67e8c3") },
  { id: "g08", label: "Graphite", src: "/backgrounds/g08.svg", swatch: grad("#2c2c32", "#0c0b0a", "#0c0c0f") },
  { id: "g09", label: "Mint", src: "/backgrounds/g09.svg", swatch: grad("#0f766e", "#34d399", "#d9f99d") },
  { id: "g10", label: "Rose", src: "/backgrounds/g10.svg", swatch: grad("#7a1f4b", "#d6467f", "#ffc4d6") },
  { id: "g11", label: "Amber", src: "/backgrounds/g11.svg", swatch: grad("#7c3a00", "#e0891a", "#fcd34d") },
  { id: "g12", label: "Slate", src: "/backgrounds/g12.svg", swatch: grad("#1e293b", "#475569", "#94a3b8") },
  { id: "g13", label: "Coral", src: "/backgrounds/g13.svg", swatch: grad("#ff6a3d", "#ff9068", "#ffd0b5") },
  { id: "g14", label: "Indigo", src: "/backgrounds/g14.svg", swatch: grad("#1e1b4b", "#4338ca", "#818cf8") },
  { id: "g15", label: "Sage", src: "/backgrounds/g15.svg", swatch: grad("#3f5540", "#7c9a72", "#cfe0b8") },
  { id: "g16", label: "Mono", src: "/backgrounds/g16.svg", swatch: grad("#f5f5f7", "#d8d8dd", "#b4b4bc") },
];

/**
 * The four ids this app shipped before the catalogue grew. Their SVGs are
 * still generated (as byte-identical copies), so a stored
 * `{ src: "/backgrounds/mint.svg", presetId: "mint" }` — which is what
 * `DEFAULT_FRAME` still is — keeps rendering; this map is only how the picker
 * knows which swatch to ring.
 */
export const PRESET_ALIASES: Record<string, string> = {
  sunset: "g06",
  ocean: "g07",
  graphite: "g08",
  mint: "g09",
};

/** Canonical catalogue id for a stored `presetId`, legacy ids included. */
export function resolvePresetId(id: string | undefined): string | undefined {
  if (!id) return undefined;
  return PRESET_ALIASES[id] ?? id;
}

/** Solid colours offered next to the gradients. */
export const COLOR_SWATCHES = [
  "#0c0b0a",
  "#1c1b19",
  "#0f172a",
  "#134e4a",
  "#7c2d12",
  "#3f7d5c",
  "#f5f3ee",
];
